<?php

declare(strict_types=1);

namespace App\Actions\Documents;

use App\Enums\DocumentType;
use App\Jobs\GeneratePdfDocument;
use App\Models\DocumentTemplate;
use App\Models\IssuedDocument;
use App\Models\Member;
use App\Services\Numbering\DocumentNumberGenerator;
use InvalidArgumentException;

/**
 * Shared core of IssueIdCard / IssueAppointmentLetter / IssueCertificate —
 * the three differ only in which template type they issue and what `title`
 * they set, so this is where the real work lives.
 *
 * Creates the `issued_documents` row (status `queued`) with `snapshot_data`
 * frozen from the member's current state, then dispatches the PDF job.
 * `snapshot_data` is what makes a 2026 appointment letter immune to the
 * member's 2027 department transfer — see docs/02-DATABASE-SCHEMA.md §4.
 */
final class IssueDocument
{
    public function __construct(
        private readonly DocumentNumberGenerator $numbers,
    ) {}

    public function handle(
        Member $member,
        DocumentType $type,
        string $title,
        int $issuedByUserId,
        ?DocumentTemplate $template = null,
        ?string $validUntil = null,
    ): IssuedDocument {
        $template ??= DocumentTemplate::query()
            ->where('type', $type->value)
            ->where('is_default', true)
            ->where('is_active', true)
            ->first();

        if (! $template) {
            throw new InvalidArgumentException("No active default template for document type '{$type->value}'.");
        }

        $documentNumber = $this->numbers->next($type);

        // `uuid` is deliberately not mass-assignable (see IssuedDocument's
        // $fillable) — it's generated by the HasUuid trait's `creating` hook,
        // same as every other public-identity column in this codebase. The
        // QR payload URL can only be built AFTER that id exists, hence the
        // create-then-update instead of computing it upfront.
        $document = IssuedDocument::query()->create([
            'document_number' => $documentNumber,
            'type' => $type->value,
            'member_id' => $member->id,
            'template_id' => $template->id,
            'title' => $title,
            'snapshot_data' => $this->snapshot($member),
            'qr_payload' => '',
            'issued_by_user_id' => $issuedByUserId,
            'issued_on' => now()->toDateString(),
            'valid_until' => $validUntil,
            'status' => 'queued',
        ]);

        $document->update(['qr_payload' => route('verify.show', ['uuid' => $document->uuid])]);

        GeneratePdfDocument::dispatch($document->id);

        return $document;
    }

    /**
     * @return array<string, mixed>
     */
    private function snapshot(Member $member): array
    {
        return [
            'name' => $member->user->name,
            'email' => $member->user->email,
            'phone' => $member->user->phone,
            'member_code' => $member->member_code,
            'department' => $member->department?->name,
            'designation' => $member->designation?->title,
            'photo_path' => $member->photo_path,
            'blood_group' => $member->blood_group,
            'joined_on' => $member->joined_on?->toDateString(),
            'status' => $member->status->value,
        ];
    }
}
