<?php

declare(strict_types=1);

namespace App\Exports\Concerns;

use App\Services\Settings\SettingsRepository;
use Illuminate\Support\Facades\Auth;
use Maatwebsite\Excel\Events\AfterSheet;

/**
 * "Every export carries a header block: NGO name, report title, date
 * range, generated-at timestamp, generated-by user. An exported file that
 * lands in an inbox with no context is a file someone will misread." See
 * docs/modules/M12-reports-analytics.md.
 *
 * Implemented as an `AfterSheet` row-insert rather than `WithCustomStartCell`
 * so it composes with `WithHeadings` — the heading row and the mapped data
 * both stay written at their normal position, then five rows get inserted
 * above them once the sheet exists.
 */
trait HasReportHeader
{
    abstract public function reportTitle(): string;

    abstract public function reportRange(): string;

    /**
     * @return array<string, callable>
     */
    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function (AfterSheet $event): void {
                $sheet = $event->sheet->getDelegate();
                $sheet->insertNewRowBefore(1, 5);

                $orgName = app(SettingsRepository::class)->get('org.name');

                $sheet->setCellValue('A1', (string) $orgName);
                $sheet->setCellValue('A2', $this->reportTitle());
                $sheet->setCellValue('A3', $this->reportRange());
                $sheet->setCellValue('A4', 'Generated at: '.now()->format('d M Y, H:i').' IST');
                $sheet->setCellValue('A5', 'Generated by: '.Auth::user()->name);
            },
        ];
    }
}
